language: ruby
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c2044eca72685a9b2ef7
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
rvm:
  - 2.1.1
before_script:
  - psql -c 'create database supermarket_test;' -U postgres
  - cp .env.example .env
  - bundle exec rake db:schema:load
bundler_args: --without development
script:
  - bundle exec rspec
  - bundle exec rubocop
services:
  - redis-server
env:
  global:
    secure: "rzoy57s+oxvw27HStU1VNHN7fS525ocQo11bmASbwG5Ax6I4X/dwWofQCoZPoGrXisMw5RQaa7e3bHJpATZsMJC67Sf6gbfSOIYY7tISXuCFh9q/19YPGltdwZkP3OgawEpufA8zcMHzD5nvWNXq4c4TKRdtX6mHQVIAOJ9u6qY="
