branches:
  only:
    - master

sudo: false

cache:
  apt: true
  bundler: true
  directories:
    - $HOME/tools
    - "$TRAVIS_BUILD_DIR/src/$NAME/vendor/bundle"
    - src/supermarket/vendor/bundle
    - src/supermarket/engines/fieri/vendor/bundle

before_install:
  - curl https://raw.githubusercontent.com/chef/ci-studio-common/pre-1.0/install.sh | bash
  - export PATH="$PATH:$HOME/ci-studio-common/bin:$HOME/tools/bin"

env:
  global:
    - CAPYBARA_SCREENSHOT_TO_S3=true
    - secure: zmBguz2BE0upyqhYJbr73wXVPkLO8Me1WisL4bh6B+HVAK6fCHSkdf/FGiiGz1h+HLF39K8DweNw7uPoyQfDxpN3E14MCUkk+jG7I+0IyT5istEsLeJXEBDp2sqgBYcPpCvw73Q4SGYsG2Uf+Ofz5ihKTw4zaxYGYkbuJ7UAs80=
    - secure: RfOhiaSlkbK0x798woj4sASE0VM2gGn6tdUqkWLWeOYvlRT1wqWs8ZLrVALfpyDiutFyxSPFIALp1fObCBTzswOtBxAQXc347dqVbYmqH92VbTp+qSJO9+dOHIoGe9hrV89Fe73AeL85n2rXzPEXLSJoE3Ap4F8nAGbkpbSf/+M=

language: ruby
rvm:
  - 2.5.3
bundler_args: "--without development --jobs 7"

notifications:
  email: false
  slack:
    secure: BfVg7BimLzBORMe8MmiBFghvq3znxSg4pQbCBiN62wCx5D9qTDLr4pvDgPZkuPqSGjUe9hB0Y0tQACqScbDLZx7IqP8+Naf5sQ4SvjNUjEMc+fQ2RJg5VqmSchgJlC4h6xwW4ArJ0Gms74Ov9klHBJQ3nzqAOV0y8Yk5Sv3FNcw=

matrix:
  include:

    # Supermarket Spec
    - env:
        - NAME=supermarket
      addons:
        postgresql: '9.3'
        apt:
          packages:
            - libxslt1-dev
            - libxml2-dev
            - libmagic-dev
      services:
        - redis-server
        - postgresql
      before_install:
        - gem install bundler --no-ri --no-rdoc
        - cd $TRAVIS_BUILD_DIR/src/$NAME && bundle config build.nokogiri --use-system-libraries
      before_script:
        - psql -c 'create database supermarket_test;' -U postgres
        - cd $TRAVIS_BUILD_DIR/src/$NAME && bundle exec rake db:schema:load
      script:
        - cd $TRAVIS_BUILD_DIR/src/$NAME
        - bundle exec rake spec
        - bundle exec rubocop
        - bundle exec bundle-audit check --update

    # Fieri Spec
    - env:
        - NAME=fieri
      addons:
        postgresql: '9.3'
        apt:
          packages:
            - libxslt1-dev
            - libxml2-dev
            - libmagic-dev
      services:
        - redis-server
        - postgresql
      before_install:
        - gem install bundler --no-ri --no-rdoc
        - cd $TRAVIS_BUILD_DIR/src/supermarket/engines/$NAME && bundle config build.nokogiri --use-system-libraries
      script:
        - cd $TRAVIS_BUILD_DIR/src/supermarket/engines/$NAME
        - bundle exec rake spec
        - bundle exec rubocop
        - bundle exec bundle-audit check --update

    # Terraform Lint
    - env:
        - NAME=lint-terraform
      install: install-tool terraform
      before_script: cd terraform
      script: make lint

    # supermarket-deploy-cookbook-cookstyle
    - env:
        - NAME=lint-supermarket-deploy-cookbook-cookstyle
      addons:
        apt:
          sources:
            - chef-stable-trusty
          packages:
            - chefdk
      cache:
        directories:
          - $HOME/.berkshelf
      install:
        - eval "$(/opt/chefdk/bin/chef shell-init bash)"
      before_script: cd cookbooks/supermarket-deploy
      script: chef exec cookstyle

    # supermarket-deploy-cookbook-foodcritic
    - env:
        - NAME=supermarket-deploy-cookbook-foodcritic
      addons:
        apt:
          sources:
            - chef-stable-trusty
          packages:
            - chefdk
      cache:
        directories:
          - $HOME/.berkshelf
      install:
        - eval "$(/opt/chefdk/bin/chef shell-init bash)"
      before_script: cd cookbooks/supermarket-deploy
      script: chef exec foodcritic . -t ~supermarket

    # omnibus-supermarket-reconfigure-cookstyle
    - env:
        - NAME=lint-omnibus-supermarket-reconfigure-cookstyle
      addons:
        apt:
          sources:
            - chef-stable-trusty
          packages:
            - chefdk
      cache:
        directories:
          - $HOME/.berkshelf
      install:
        - eval "$(/opt/chefdk/bin/chef shell-init bash)"
      before_script: cd omnibus/cookbooks/omnibus-supermarket
      script: chef exec cookstyle

    # omnibus-supermarket-reconfigure-foodcritic
    - env:
        - NAME=omnibus-supermarket-reconfigure-foodcritic
      addons:
        apt:
          sources:
            - chef-stable-trusty
          packages:
            - chefdk
      cache:
        directories:
          - $HOME/.berkshelf
      install:
        - eval "$(/opt/chefdk/bin/chef shell-init bash)"
      before_script: cd omnibus/cookbooks/omnibus-supermarket
      script: chef exec foodcritic . -t ~supermarket

    # omnibus-supermarket-reconfigure-unit
    - env:
        - NAME=omnibus-supermarket-reconfigure-unit
      addons:
        apt:
          sources:
            - chef-stable-trusty
          packages:
            - chefdk
      cache:
        directories:
          - $HOME/.berkshelf
      install:
        - eval "$(/opt/chefdk/bin/chef shell-init bash)"
      before_script: cd omnibus/cookbooks/omnibus-supermarket
      script: chef exec rspec
