before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libxslt-dev libxml2-dev
  - bundle config build.nokogiri --use-system-libraries
before_script:
  - psql -c 'create database supermarket_test;' -U postgres
  - psql supermarket_test -c 'create extension pg_trgm' -U postgres
  - bundle exec rake db:schema:load
bundler_args: --without development --jobs 7
cache:
  - apt
  - bundler
env:
  global:
    secure: "rzoy57s+oxvw27HStU1VNHN7fS525ocQo11bmASbwG5Ax6I4X/dwWofQCoZPoGrXisMw5RQaa7e3bHJpATZsMJC67Sf6gbfSOIYY7tISXuCFh9q/19YPGltdwZkP3OgawEpufA8zcMHzD5nvWNXq4c4TKRdtX6mHQVIAOJ9u6qY="
language: ruby
notifications:
  email: false
  webhooks:
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
    on_success: change  # options: [always|never|change] default: always
    urls:
      - https://webhooks.gitter.im/e/c2044eca72685a9b2ef7
rvm:
  - 2.1.3
script:
  - bundle exec rake spec
  - bundle exec rake spec:rubocop
  - bundle exec bundle-audit check --update
services:
  - redis-server
