# Documentation available at https://expeditor.chef.io/docs/getting-started/
---

project:
  alias: supermarket

# The name of the product keys for this product (from mixlib-install)
product_key: supermarket

# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: supermarket-notify

automate:
  organization: products
  project: supermarket

github:
  # The file where our CHANGELOG is kept. This file is updated automatically with
  # details from the Pull Request via the `built_in:update_changelog` merge_action.
  changelog_file: "CHANGELOG.md"
  # clean up PR branches when they've merged
  delete_branch_on_merge: true
  # allow bumping the minor release via label
  minor_bump_labels:
    - "Expeditor: Bump Version Minor"
  # allow bumping the major release via label
  major_bump_labels:
    - "Expeditor: Bump Version Major"
  # The file where the MAJOR.MINOR.PATCH version is kept. The version in this file
  # is bumped automatically via the `built_in:bump_version` merge_action.
  version_file: "VERSION"

changelog:
  rollup_header: Changes not yet released to stable
  categories:
    - "Aspect: Correctness": "Bug Fixes"
    - "Aspect: Security": "Security Fixes"
    - "Type: Breaking Change": "Breaking Changes"
    - "Type: Bug": "Bug Fixes"
    - "Type: Chore": "Maintenance Updates"
    - "Type: Deprecation": "Deprecations"
    - "Type: Enhancement": "Enhancements"
    - "Type: Regression": "Bug Fixes"
    - "Type: Tech Debt": "Maintenance Updates"

pipelines:
  - habitat/build
  - verify:
      public: true
      definition: .expeditor/verify.habitat-packages.yml
  - omnibus/release
  - omnibus/adhoc:
      definition: .expeditor/release.omnibus.yml
      env:
        - ADHOC: true

subscriptions:
  # These actions are taken, in order they are specified, anytime a Pull Request is merged.
  - workload: pull_request_merged:{{github_repo}}:{{release_branch}}:*
    actions:
      - built_in:bump_version:
          ignore_labels:
            - "Expeditor: Skip Version Bump"
            - "Expeditor: Skip All"
            - "Aspect: Documentation"
      - built_in:update_changelog:
          ignore_labels:
            - "Expeditor: Skip Changelog"
            - "Expeditor: Skip All"
            - "Aspect: Documentation"
      - trigger_pipeline:omnibus/release:
          ignore_labels:
            - "Expeditor: Skip Omnibus"
            - "Expeditor: Skip All"
            - "Aspect: Documentation"
          only_if: built_in:bump_version
      - trigger_pipeline:habitat/build:
          ignore_labels:
            - "Expeditor: Skip All"
            - "Aspect: Documentation"

  # These actions are taken, in the order specified, when an Omnibus artifact is promoted
  # within Chef's internal artifact storage system.
  #
  # TODO: add promoted_to_unstable action to update changelog with modified omnibus components

  - workload: artifact_published:stable:supermarket:*
    actions:
      - built_in:rollover_changelog
      - bash:.expeditor/publish-release-notes.sh
      - bash:.expeditor/announce-release.sh
      - built_in:notify_chefio_slack_channels

  - workload: project_promoted:{{agent_id}}:*
    actions:
      - built_in:promote_artifactory_artifact

  - workload: buildkite_hab_build_group_published:{{agent_id}}:*
    actions:
      - built_in:promote_habitat_packages

artifact_channels:
  - unstable
  - current
  - stable
