#
# Register your application's keys and secrets.
# This file is powered by ENV variables. For local development, create and
# configure a .env (dotenv: https://github.com/bkeepers/dotenv) file
# When deploying to a PaaS, like Heroku, simply set the ENV variables.
#
# An example using GitHub
#
#
#   github:
#     key: <%= ENV['GITHUB_OAUTH_KEY'] %>
#     secret: <%= ENV['GITHUB_OAUTH_SECRET'] %>
#

development:
  icla_version: '99999-2621/LEGAL14767024.1'
  ccla_version: '99999-2621/LEGAL14767024.1'
  cla_signature_notification_email: <%= ENV['CLA_SIGNATURE_NOTIFICATION_EMAIL'] %>
  from_email: <%= ENV['FROM_EMAIL'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  host: <%= ENV['HOST'] %>
  port: <%= ENV['PORT'] %>
  sentry_url: <%= ENV['SENTRY_URL'] %>
  statsd:
    host: <%= ENV['STATSD_HOST'] %>
    port: <%= ENV['STATSD_PORT'] %>
    namespace: <%= ENV['STATSD_NAMESPACE'] %>
  github:
    access_token: <%= ENV['GITHUB_ACCESS_TOKEN'] %>
  omniauth:
    github:
      key: <%= ENV['GITHUB_KEY'] %>
      secret: <%= ENV['GITHUB_SECRET'] %>
    chef_oauth2:
      app_id: <%= ENV['CHEF_OAUTH2_APP_ID'] %>
      secret: <%= ENV['CHEF_OAUTH2_SECRET'] %>
      site: <%= ENV['CHEF_OAUTH2_SITE'] %>
  pubsubhubbub:
    callback_url: "http://currybowl.herokuapp.com/52f2934cec5edd0002000015"
    hub_secret: <%= ENV['PUBSUBHUBBUB_SECRET'] %>
  smtp:
    address: <%= ENV['SMTP_ADDRESS'] %>
    port: <%= ENV['SMTP_PORT'] %>
    user_name: <%= ENV['SMTP_USER_NAME'] %>
    password: <%= ENV['SMTP_PASSWORD'] %>
  curry:
    success_label: 'Signed CLA'
    cla_location: <%= ENV['CURRY_CLA_LOCATION'] || 'https://community.getchef.com' %>
  s3:
    bucket: <%= ENV['S3_BUCKET'] %>
    access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['S3_SECRET_ACCESS_KEY'] %>

production:
  icla_version: '99999-2621/LEGAL14767024.1'
  ccla_version: '99999-2621/LEGAL14767024.1'
  cla_signature_notification_email: <%= ENV['CLA_SIGNATURE_NOTIFICATION_EMAIL'] %>
  from_email: <%= ENV['FROM_EMAIL'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  host: <%= ENV['HOST'] %>
  port: <%= ENV['PORT'] %>
  sentry_url: <%= ENV['SENTRY_URL'] %>
  statsd:
    host: <%= ENV['STATSD_HOST'] %>
    port: <%= ENV['STATSD_PORT'] %>
    namespace: <%= ENV['STATSD_NAMESPACE'] %>
  github:
    access_token: <%= ENV['GITHUB_ACCESS_TOKEN'] %>
  omniauth:
    github:
      key: <%= ENV['GITHUB_KEY'] %>
      secret: <%= ENV['GITHUB_SECRET'] %>
    chef_oauth2:
      app_id: <%= ENV['CHEF_OAUTH2_APP_ID'] %>
      secret: <%= ENV['CHEF_OAUTH2_SECRET'] %>
      site: <%= ENV['CHEF_OAUTH2_SITE'] %>
  pubsubhubbub:
    hub_secret: <%= ENV['PUBSUBHUBBUB_SECRET'] %>
  segment_io_write_key: <%= ENV['SEGMENT_IO_WRITE_KEY'] %>
  smtp:
    address: <%= ENV['SMTP_ADDRESS'] %>
    port: <%= ENV['SMTP_PORT'] %>
    user_name: <%= ENV['SMTP_USER_NAME'] %>
    password: <%= ENV['SMTP_PASSWORD'] %>
  curry:
    success_label: 'Signed CLA'
    cla_location: <%= ENV['CURRY_CLA_LOCATION'] || 'https://community.getchef.com' %>
  s3:
    bucket: <%= ENV['S3_BUCKET'] %>
    access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['S3_SECRET_ACCESS_KEY'] %>

test:
  icla_version: '99999-2621/LEGAL14767024.1'
  ccla_version: '99999-2621/LEGAL14767024.1'
  cla_signature_notification_email: <%= ENV['CLA_SIGNATURE_NOTIFICATION_EMAIL'] %>
  from_email: <%= ENV['FROM_EMAIL'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  host: <%= ENV['HOST'] %>
  port: <%= ENV['PORT'] %>
  sentry_url: <%= ENV['SENTRY_URL'] %>
  statsd:
    host: <%= ENV['STATSD_HOST'] %>
    port: <%= ENV['STATSD_PORT'] %>
    namespace: <%= ENV['STATSD_NAMESPACE'] %>
  github:
    access_token: <%= ENV['GITHUB_ACCESS_TOKEN'] %>
  pubsubhubbub:
    callback_url: "http://currybowl.herokuapp.com/52f2934cec5edd0002000015"
    hub_secret: "YOUR_PUBSUBHUBBUB_SECRET"
  omniauth:
    github:
      key: <%= ENV['GITHUB_KEY'] %>
      secret: <%= ENV['GITHUB_SECRET'] %>
    chef_oauth2:
      app_id: <%= ENV['CHEF_OAUTH2_APP_ID'] %>
      secret: <%= ENV['CHEF_OAUTH2_SECRET'] %>
      site: <%= ENV['CHEF_OAUTH2_SITE'] %>
  curry:
    success_label: 'Signed CLA'
    cla_location: 'https://community.getchef.com'
  s3:
    bucket: <%= ENV['S3_BUCKET'] %>
    access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['S3_SECRET_ACCESS_KEY'] %>
