#
# Register your applications and add the appropiate keys and secrets.
#
# An example using GitHub
#
#   github:
#     key: MY_KEY
#     secret: MY_SECRET
#
# This file is actually parsed as ERB first, so you can use environment
# variables too:
#
#   github:
#     key: <%= ENV['GITHUB_OAUTH_KEY'] %>
#     secret: <%= ENV['GITHUB_OAUTH_SECRET'] %>
#

development:
  icla_version: '99999-2621/LEGAL14767024.1'
  ccla_version: '99999-2621/LEGAL14767024.1'
  omni_auth:
    github:
      key: YOUR_KEY
      secret: YOUR_SECRET

production:
  icla_version: '99999-2621/LEGAL14767024.1'
  ccla_version: '99999-2621/LEGAL14767024.1'
  omni_auth:
    github:
      key: YOUR_KEY
      secret: YOUR_SECRET

test:
  icla_version: '99999-2621/LEGAL14767024.1'
  ccla_version: '99999-2621/LEGAL14767024.1'
  omni_auth:
    github:
      key: YOUR_KEY
      secret: YOUR_SECRET
