development:
  adapter: postgresql
  database: supermarket_development
  host: <%= ENV['POSTGRES_IP'] || 'localhost' %>
  pool: 30

test:
  adapter: postgresql
  database: supermarket_test
  host: <%= ENV['POSTGRES_IP'] || 'localhost' %>

production:
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  adapter: postgresql
  database: supermarket_production
